<h3>Testimonial Create Form</h3>
<div class="testimonial-create-form">
    <form class="testimonial-blog-create" method="post" enctype="multipart/form-data" action="<?= $block->getUrl('testimonials/testimonial/save')?>">
        <div class="testimonial-blog-create-right">
            <img src="" alt="" class="image-upload" />
        </div>

        <div class="testimonial-blog-create-left">
            <label for="blog_name">First Name</label>
            <input type="text" name="name" placeholder="Your name..">

            <label for="blog_email">Email</label>
            <input type="text" name="email" placeholder="Your email..">

            <label for="blog_designation">Designation</label>
            <input type="text" name="designation" placeholder="Your designation..">

            <label for="blog_contact">Contact</label>
            <input type="number" name="contact" placeholder="Your contact..">

            <label for="blog_message">Message</label>
            <textarea name="message" rows="10" cols="30" placeholder="This is your message.."></textarea>

            <div class="field image">
                <div class="control">
                    <input name="image" id="image" title="<?php /* @escapeNotVerified */ echo __('image') ?>"   type="file" />
                </div>
            </div>
            <label for="category_id">Category</label>
            <select name="category_id">
                <?php
                foreach ($block->getAll() as $item) {
                        ?><option label="<?php echo $item->getCategory_name(); ?>">
                        <?php echo $item->getCategory_id(); ?>
                        </option>                 
                    <?php
                }
                ?>
            </select>
            <input type="submit" name="createBtn" class="createBtn" value="Submit">
        </div>
    </form>
</div>